### PR TITLE
feat(prometheus): add node-problem-detector to prometheus addon

### PR DESCRIPTION
**Pull request by kevinfeng**
Signed-off-by: Feng Kun <fengkun32@gmail.com>

**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**:
add node-problem-detector to prometheus addon, default disabled

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by kevinfeng** [comment]
image
images is pushed

**Comment by QianChenglong** [comment]
Need support multi arch

**Comment by kevinfeng** [comment]
amd64 done
image

**Pull request merged**
