### PR TITLE
feat(installer): support access console by ip

### PR DESCRIPTION
**Pull request by lkxjtu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind feature

**What this PR does / why we need it**:
Can't access console by ip. This PR add default route to tke-gateway for ingress-nginx 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by leoryu** [comment]
Thx for your contribution. We have already support access console through :30080 and :30443. I think there is no necessary to add this default rule.

**Comment by lkxjtu** [comment]
That is ok

**Comment by lkxjtu** [comment]
> Thx for your contribution. We have already support access console through :30080 and :30443. I think there is no necessary to add this default rule.

That is ok，thanks

**Comment by leoryu** [comment]
> Thx for your contribution. We have already support access console through :30080 and :30443. I think there is no necessary to add this default rule.

@lkxjtu I have checked the latest code, I found I missed something.

**Comment by lkxjtu** [comment]
> 

No problem at present, I can access the console by <vip>:31180, just use it in the test environment

**Pull request closed without merging**
