### PR TITLE
fix(installer): support all in one install

### PR DESCRIPTION
**Pull request by huxiaoliang**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by davidwtf** [comment]
@huxiaoliang Can you explain why change `live-restore` to `false`?
For the `all in  one` case, we use a script like this to handle docker daemon restart, which need `live-restore` is `true`:
```
#!/bin/bash

docker_id=$(docker run -d ...<some other args>... \
tkestack/tke-installer:v1.3.0)

docker logs -f ${docker_id}

# wait docker restart
while true; do
   sleep 1
   info=$(docker info)
   if [[ "$?" == "0" ]]; then
       break
   fi
done

docker logs --tail 0 -f ${docker_id}
docker rm -f ${docker_id}
```

**Comment by huxiaoliang** [comment]
@davidwtf  this change allow installer container get restarted when docker daemon reload, so that the docker.sock always available  for `docker`  command in all in one case,  if you depend on `live-restore` feature,  I will change this pr to `restart` installer  container inside container to support all in one case.

**Comment by davidwtf** [comment]
@huxiaoliang thanks. LGTM

**Pull request merged**
