### PR TITLE
feat(platform): crypto ssh info

### PR DESCRIPTION
**Pull request by leoryu**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by huxiaoliang** [comment]
@davidwtf  please help review

**Comment by huxiaoliang** [comment]
@leoryu  btw, could you please investigate how k8s handle credential info by `DATA+OMITTED ` and `--raw` the as well? thanks


```
root@VM-0-80-ubuntu:/etc/kubernetes/manifests# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:6443
  name: global
contexts:
- context:
    cluster: global
    user: kubernetes-admin
  name: kubernetes-admin@global
current-context: kubernetes-admin@global
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    token: 1m6CJoJ1BQZcQMQOKdlwbPnjS2W
root@VM-0-80-ubuntu:/etc/kubernetes/manifests# kubectl config view --raw
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01USXlOREV3TVRJeU1sb1hEVE13TVRJeU1qRXdNVEl5TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGsvCkdPR1FCSnlURGR1cFlYL3RjRE1OU1h6eERJak9SZ3pzN0lzWVBpZ3JRRVREcEdKZGl4eFB4RDBpMVpmL1VxRDcKTVJleW12NEd0dzVQazQxbVFLMkplME5peTBJS0d4aDl4QXVIdjRwa1ZWaGcvSXBTNFFzbHN1MG0yNU1KSWtqdApraFRrRHdpa2U3SEs1YnhqM0VZZGRSOHlPNHFNV2MzaXAvRVRzTU5FSHJHT2xjQXdjbExSMy94bkRHTTVQaDdaCjhPbmFPcm9YMm5sODk0MjVFTmtSOUEyZ0pEYmpHTUVoQUQ5OTVicWJyNld3UXpsNHJmWjVoSkdJbkEydFZ6NlEKM0ZlQUFrcHZvMERpbjdkbzJDa3Nnek0ycFVEQkgvalNhcWhOblZVcU9IOEtEdnF1VTc4TXV0UlVzNnJNemhJTworR3M1VXhRNy9VZ1BiUjhlUVpjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMWW11dnFyTExXMlcrZU51NlhWYkFlV1Z5cUcKR2FpNzA2MTN2SzhZakQ4anlLaFZCalJIS3RRcDJmb2tTbW5UTlJINFlFWVpFQnZCUWgxT01sYXlaQWtleHBTbQpKbmZpY3JoR3lJb3lqNmJsdXZHVUFvK3B3aisxMCtaYzlPSDB0SnFXK2EvT1VhaWJtSnA0R201YWtjYkZOSk1WCmt6TC9DQ0FiM3A4eTI4RGV2aEpiL295cDgyWGN5QTdHRHh5K2l3bytWa1lRTzhtQmtWMGJkUXZhajlMdFRmdUoKcjh2bzBtL1hTcmw5OEhMT1ZIak5KWW5IbDNUb29sT3VMN0k3TlJUbXorWW51VmtiQzFOS2F6ejQveUdjTFhmcgpFVjlIVm1NRkc0bWpjY1JCK2lXOVo1Q3Fpb3J5aVBPeU1rSHVvcFo2TStpS0dtTlVwK1ZEUHk3VkxFND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://127.0.0.1:6443
  name: global
contexts:
- context:
    cluster: global
    user: kubernetes-admin
  name: kubernetes-admin@global
current-context: kubernetes-admin@global
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    token: 1m6CJoJ1BQZcQMQOKdlwbPnjS2W
root@VM-0-80-ubuntu:/etc/kubernetes/manifests# 
```

**Comment by leoryu** [comment]
> @leoryu btw, could you please investigate how k8s handle credential info by `DATA+OMITTED ` and `--raw` as well? thanks
> 
> ```
> root@VM-0-80-ubuntu:/etc/kubernetes/manifests# kubectl config view
> apiVersion: v1
> clusters:
> - cluster:
>     certificate-authority-data: DATA+OMITTED
>     server: https://127.0.0.1:6443
>   name: global
> contexts:
> - context:
>     cluster: global
>     user: kubernetes-admin
>   name: kubernetes-admin@global
> current-context: kubernetes-admin@global
> kind: Config
> preferences: {}
> users:
> - name: kubernetes-admin
>   user:
>     token: 1m6CJoJ1BQZcQMQOKdlwbPnjS2W
> root@VM-0-80-ubuntu:/etc/kubernetes/manifests# kubectl config view --raw
> apiVersion: v1
> clusters:
> - cluster:
>     certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01USXlOREV3TVRJeU1sb1hEVE13TVRJeU1qRXdNVEl5TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGsvCkdPR1FCSnlURGR1cFlYL3RjRE1OU1h6eERJak9SZ3pzN0lzWVBpZ3JRRVREcEdKZGl4eFB4RDBpMVpmL1VxRDcKTVJleW12NEd0dzVQazQxbVFLMkplME5peTBJS0d4aDl4QXVIdjRwa1ZWaGcvSXBTNFFzbHN1MG0yNU1KSWtqdApraFRrRHdpa2U3SEs1YnhqM0VZZGRSOHlPNHFNV2MzaXAvRVRzTU5FSHJHT2xjQXdjbExSMy94bkRHTTVQaDdaCjhPbmFPcm9YMm5sODk0MjVFTmtSOUEyZ0pEYmpHTUVoQUQ5OTVicWJyNld3UXpsNHJmWjVoSkdJbkEydFZ6NlEKM0ZlQUFrcHZvMERpbjdkbzJDa3Nnek0ycFVEQkgvalNhcWhOblZVcU9IOEtEdnF1VTc4TXV0UlVzNnJNemhJTworR3M1VXhRNy9VZ1BiUjhlUVpjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMWW11dnFyTExXMlcrZU51NlhWYkFlV1Z5cUcKR2FpNzA2MTN2SzhZakQ4anlLaFZCalJIS3RRcDJmb2tTbW5UTlJINFlFWVpFQnZCUWgxT01sYXlaQWtleHBTbQpKbmZpY3JoR3lJb3lqNmJsdXZHVUFvK3B3aisxMCtaYzlPSDB0SnFXK2EvT1VhaWJtSnA0R201YWtjYkZOSk1WCmt6TC9DQ0FiM3A4eTI4RGV2aEpiL295cDgyWGN5QTdHRHh5K2l3bytWa1lRTzhtQmtWMGJkUXZhajlMdFRmdUoKcjh2bzBtL1hTcmw5OEhMT1ZIak5KWW5IbDNUb29sT3VMN0k3TlJUbXorWW51VmtiQzFOS2F6ejQveUdjTFhmcgpFVjlIVm1NRkc0bWpjY1JCK2lXOVo1Q3Fpb3J5aVBPeU1rSHVvcFo2TStpS0dtTlVwK1ZEUHk3VkxFND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
>     server: https://127.0.0.1:6443
>   name: global
> contexts:
> - context:
>     cluster: global
>     user: kubernetes-admin
>   name: kubernetes-admin@global
> current-context: kubernetes-admin@global
> kind: Config
> preferences: {}
> users:
> - name: kubernetes-admin
>   user:
>     token: 1m6CJoJ1BQZcQMQOKdlwbPnjS2W
> root@VM-0-80-ubuntu:/etc/kubernetes/manifests# 
> ```

This is handled by kubectl in client side through overwrite the credential info.

**Comment by huxiaoliang** [comment]
@leoryu  if we porting the kubectl logic to platform-api, what is the code change and effort?

**Comment by huxiaoliang** [comment]
@leoryu  please take a look https://segmentfault.com/a/1190000017129467 and try open source solution or customized serialization on `string` field encrypt and decrypt.

**Comment by huxiaoliang** [comment]
@leoryu comments from @davidwtf: put the key the `ClusterCredential`,  the key is random string,  
if ClusterCredential has the key，then get password from that key, if no key,  no need decode password, i also prefer to this solution

**Comment by huxiaoliang** [comment]
close it now since the solution is ugly, we can re-open it when we found a better solution

**Pull request closed without merging**
