### PR TITLE
fix(registry): update dependence version of github.com/docker/distribution to fix a crash bug

### LINKED ISSUE #734: tke-regisitry often crashes in the background when Tencent cos/csp was used
**What happened**:
tke-regisitry often crashes in the background

```
goroutine 11 [running]:
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk.func1(0xc0000aa400, 0xc000284001, 0xc000839998)
        /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:973 +0x9d
github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc00000c720, 0x7fdf630cf1b8, 0xc0001ee310, 0xc00045e2d0, 0xc000839a98, 0x0, 0x0, 0x0, 0x1, 0x2)
        /go/src/github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4198 +0x111
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk(0xc0002e5680, 0xefec00, 0xc0001ee2a0, 0xc000839b58, 0xc000830481, 0x20, 0xdc5475, 0x1, 0xc000358fc0, 0x0, ...)
        /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:971 +0x3a1
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).Walk(0xc0002e5680, 0xefec00, 0xc0001ee2a0, 0xc0001bc880, 0x20, 0xc000358fc0, 0x2, 0x0)
        /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:919 +0x160
github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk(0xc0003a5af0, 0xefec00, 0xc0001ee2a0, 0xc0001bc880, 0x20, 0xc000358fc0, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/storage/driver/base/base.go:239 +0x234
github.com/docker/distribution/registry/storage.getOutstandingUploads(0xefed40, 0xc0003acdc0, 0xf0a2c0, 0xc0003a5af0, 0x2, 0xc000094d40, 0xc000094e10, 0x808d3e)
        /go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:70 +0x236
github.com/docker/distribution/registry/storage.PurgeUploads(0xefed40, 0xc0003acdc0, 0xf0a2c0, 0xc0003a5af0, 0xbf05a4e3da6a338a, 0xfffddb85289fcfc6, 0x15a5680, 0xc000051701, 0xe09608, 0xc0001e3680, ...)
        /go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:34 +0x163
github.com/docker/distribution/registry/handlers.startUploadPurger.func1(0xf0ddc0, 0xc0002673b0, 0xefed40, 0xc0003acdc0, 0xf0a2c0, 0xc0003a5af0, 0x2260ff9290000, 0x0, 0x4e94914f0000)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:1071 +0x221
created by github.com/docker/distribution/registry/handlers.startUploadPurger
        /go/src/github.com/docker/distribution/registry/handlers/app.go:1064 +0x2e9
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
tke-regisitry use s3 configuration, and use Tencent Cloud cos/csp

**Anything else we need to know?**:
This is caused by 
https://github.com/docker/distribution/issues/2820

**Environment**:
- TKE version: v1.3.0
- Global or business cluster: global
- Kubernetes version (use `kubectl version`): v16.6
- Install addons: none
- Others: none

### PR DESCRIPTION
**Pull request by xenv**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Synchronize official bug fixes: https://github.com/docker/distribution/commit/0a1e4a57e241ac320b613a7d055ce166c9bb65f1

**Which issue(s) this PR fixes**:

Fixes #734

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by xenv** [comment]
no code added so the build test fail

**Comment by huxiaoliang** [comment]
@xenv  please fix build issue

```
Run make
make[1]: Entering directory '/data/actions-runner/_work/tke/tke'
===========> Run golangci to lint source codes
level=error msg="Running error: context loading failed: no go files to analyze"
make[1]: *** [go.lint] Error 5
build/lib/golang.mk:87: recipe for target 'go.lint' failed
make[1]: Leaving directory '/data/actions-runner/_work/tke/tke'
make: *** [lint] Error 2
Makefile:130: recipe for target 'lint' failed
##[error]Process completed with exit code 2.
```

**Comment by xenv** [comment]
@huxiaoliang done

**Pull request merged**
